### ISSUE TITLE
The analysis has failed. Error message: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "analyze.PatchPresentTest_new.seJs" is null

### ISSUE THREAD

**Issue by qinzhengze** [Anonymous-Phunter/PHunter#1]
Hi, when i run the program, the error is:
The analysis has failed. Error message: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "analyze.PatchPresentTest_new.seJs" is null
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "analyze.PatchPresentTest_new.seJs" is null
        at symbolicExec.MethodDigest.optimizePredicate(MethodDigest.java:531)
        at symbolicExec.MethodDigest.checkBranch(MethodDigest.java:462)
        at symbolicExec.MethodDigest.getBlockPredicate(MethodDigest.java:397)
        at symbolicExec.MethodDigest.traverseBlock(MethodDigest.java:121)
        at symbolicExec.MethodDigest.enumMethodPath(MethodDigest.java:58)
        at symbolicExec.MethodDigest.<init>(MethodDigest.java:41)
        at analyze.PatchPresentTest_new.doSimilarityCompute(PatchPresentTest_new.java:172)
        at analyze.PatchPresentTest_new.<init>(PatchPresentTest_new.java:51)
        at signTPL.MainClass.run(MainClass.java:106)
        at signTPL.MainClass.main(MainClass.java:54)

**Comment by Anonymous-Phunter** [comment]
Hi, thanks for your issue.
Please use java8 or java11 to run this project. According to my experiments, using java17 will have this problem.
